// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT0nN_j9Vf6uGcGoo8x7CHqb5lYhvhD-U',
    appId: '1:489385859664:web:83c327a362a0b7dda6cf55',
    messagingSenderId: '489385859664',
    projectId: 'prosfessorapp',
    authDomain: 'prosfessorapp.firebaseapp.com',
    storageBucket: 'prosfessorapp.firebasestorage.app',
    measurementId: 'G-JMX4Z64JF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATIauuVK0lcH0rjmc694Q1ZxVe0CcnZu4',
    appId: '1:489385859664:android:72716120ac05fb9aa6cf55',
    messagingSenderId: '489385859664',
    projectId: 'prosfessorapp',
    storageBucket: 'prosfessorapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNNfyR24hcW58GL1C9wPkyImJvadKo65o',
    appId: '1:489385859664:ios:e47e3d8148951d9ca6cf55',
    messagingSenderId: '489385859664',
    projectId: 'prosfessorapp',
    storageBucket: 'prosfessorapp.firebasestorage.app',
    iosBundleId: 'com.example.professorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNNfyR24hcW58GL1C9wPkyImJvadKo65o',
    appId: '1:489385859664:ios:e47e3d8148951d9ca6cf55',
    messagingSenderId: '489385859664',
    projectId: 'prosfessorapp',
    storageBucket: 'prosfessorapp.firebasestorage.app',
    iosBundleId: 'com.example.professorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT0nN_j9Vf6uGcGoo8x7CHqb5lYhvhD-U',
    appId: '1:489385859664:web:d2b0c560dfde27f8a6cf55',
    messagingSenderId: '489385859664',
    projectId: 'prosfessorapp',
    authDomain: 'prosfessorapp.firebaseapp.com',
    storageBucket: 'prosfessorapp.firebasestorage.app',
    measurementId: 'G-ZDXKDF32X1',
  );
}
